import{a as B,S as M,i as n}from"./assets/vendor-DTnuR-JU.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const $="51715222-245823a157b91ecf18a5e059a",E="https://pixabay.com/api/";async function f(o,r=1,s=15){const a={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s};return(await B.get(E,{params:a})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more");let O=new M(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:i,comments:q,downloads:v})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${q}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),O.refresh()}function H(){m.innerHTML=""}function g(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function b(){y.classList.remove("hidden")}function S(){y.classList.add("hidden")}function P(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const w=document.querySelector(".form"),x=document.querySelector(".load-more");let l="",c=1;const u=15;let d=0;w.addEventListener("submit",A);x.addEventListener("click",D);async function A(o){if(o.preventDefault(),l=o.target.query.value.trim(),!l){n.error({message:"Введіть пошуковий запит"});return}c=1,H(),S(),g();try{const r=await f(l,c,u);if(d=r.totalHits,d===0){n.error({message:"Нічого не знайдено"});return}h(r.hits),d>u?b():n.info({message:"Ви досягли кінця результатів пошуку"})}catch{n.error({message:"Сталася помилка. Спробуйте ще раз."})}finally{L(),w.reset()}}async function D(){c+=1,S(),g();try{const o=await f(l,c,u);h(o.hits),P(),c*u<d?b():n.info({message:"Ви досягли кінця результатів пошуку"})}catch{n.error({message:"Сталася помилка. Спробуйте ще раз."})}finally{L()}}
//# sourceMappingURL=index.js.map
