import{a as q,S as B,i as s}from"./assets/vendor-CsOP1TRZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const R="51715222-245823a157b91ecf18a5e059a",$="https://pixabay.com/api/";async function f(o,r=1,a=15){const i={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a};return(await q.get($,{params:i})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const r=o.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:l,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${l}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),M.refresh()}function E(){p.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function O(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const P=document.querySelector(".form"),H=document.querySelector(".load-more");let c="",n=1;const d=15;let u=0;P.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){s.warning({title:"Увага",message:"Введіть пошуковий запит!",position:"topRight"});return}n=1,E(),w(),y();try{const r=await f(c,n,d);if(u=r.totalHits,r.hits.length===0){s.info({title:"Немає результатів",message:"Спробуйте інший запит.",position:"topRight"});return}g(r.hits),n*d<u?b():s.info({title:"Кінець результатів",message:"Більше зображень немає.",position:"topRight"})}catch{s.error({title:"Помилка",message:"Не вдалося завантажити зображення.",position:"topRight"})}finally{L()}});H.addEventListener("click",async()=>{n+=1,w(),y();try{const o=await f(c,n,d);g(o.hits),O(),n*d<u?b():s.info({title:"Кінець результатів",message:"Всі зображення вже завантажені.",position:"topRight"})}catch{s.error({title:"Помилка",message:"Не вдалося завантажити додаткові зображення.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
