import{a as S,S as v,i as s}from"./assets/vendor-2NRXftFG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const q="51715222-245823a157b91ecf18a5e059a",E="https://pixabay.com/api/";async function u(r,o=1){const i={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await S.get(E,{params:i})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const o=r.map(({webformatURL:i,largeImageURL:n,tags:e,likes:t,views:a,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function P(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function $(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const M=document.querySelector("#search-form"),R=document.querySelector(".load-more");let c="",l=1,d=0;M.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.query.value.trim(),!c){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}l=1,P(),L(),h();try{const o=await u(c,l);if(d=o.totalHits,!o.hits.length){s.error({title:"Error",message:"Sorry, no images found. Try again!",position:"topRight"});return}g(o.hits),l*15<d&&$()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});R.addEventListener("click",async()=>{l+=1,h();try{const r=await u(c,l);g(r.hits),document.querySelectorAll(".gallery-item").length>=d&&(L(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
